parent_config: "configs/exp_kitti_10000_cam_single_opa_pose_higs_hybrid_3dgrut.yaml"

exp_name: "kitti_center_10000_cam_single_opa_pose_higs_hybrid_3dgrut_trreg1"

model:
  pose_correction:
    lambda_translation: 1.0
    lambda_rotation: 0.0
