parent_config: "configs/exp_kitti_500_cam_single_opa_gtrot_t_base.yaml"

exp_name: "kitti_center_500_cam_single_opa_gtrot_t_x020"

model:
  pose_correction:
    init_se3: [0.20, 0.0, 0.0, 0.0, 0.0, 0.0]
