parent_config: "configs/exp.yaml"

exp_name: "kitti_column_smoke"
task_name: "lidar_rt"
gpus: [3]

testing_iterations: 50
saving_iterations: [50, 100]
visual_interval: 50

lidar_origin_mode: "column_interp"

opt:
  iterations: 100
  position_lr_max_steps: 100

refine:
  use_refine: False
