parent_config: "configs/exp_kitti_3000_cam_single_opa_pose.yaml"

exp_name: "kitti_center_3000_cam_single_opa_pose_higs"

model:
  pose_correction:
    accumulate_steps: 8
    init_se3: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    lambda_translation: 0.0
    lambda_rotation: 0.0
