parent_config: "configs/exp_kitti_10000_cam_single_opa_pose_higs_hybrid_3dgrut.yaml"

exp_name: "kitti_center_10000_cam_single_opa_pose_higs_hybrid_3dgrut_rebase_anchor"

model:
  pose_correction:
    lambda_translation: 0.0
    lambda_rotation: 0.0
    lambda_translation_anchor: 0.05
    lambda_rotation_anchor: 0.0

rebase_pose_after_initial_pure_pnp: true
translation_lr_drop_cycle: 101
translation_lr_drop_factor: 0.2
