parent_config: "configs/exp_kitti_center_300.yaml"

exp_name: "kitti_center_3000"

opt:
  iterations: 3000
  position_lr_max_steps: 3000
  densify_from_iter: 500
  densify_until_iter: 2000
  densify_until_num_points: 5000000

testing_iterations: 200
saving_iterations: [1000, 3000]
visual_interval: 500
