parent_config: "configs/exp_kitti_10000_cam_single_opa_strongcam1.yaml"

opt:
  iterations: 2000
  densify_from_iter: 200
  densify_until_iter: 1500
  saving_iterations: [2000]
  testing_iterations: [2000]
