parent_config: "configs/exp_kitti_6000_cam_single_opa_pose_higs_coldstart_stage2_vismatch_matchanything_roma.yaml"

exp_name: "kitti_center_6000_cam_single_opa_pose_higs_coldstart_stage2_vismatch_matchanything_roma_allframes"

model:
  pose_correction:
    matcher_update_interval: 50
