parent_config: "configs/kitti_calib/static/5_50_t_cam_single_opa_pose_higs_default_local_data.yaml"

frame_length: [0, 29]
eval_frames: [5, 15, 25]

scene_id: kc_5_50_t_front30_cam_single_opa_pose_higs_default_gtt_fastlr
